// src/actions/wishlist.ts
export const ADD_WISHLIST_REQUEST = 'ADD_WISHLIST_REQUEST';
export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS';
export const ADD_WISHLIST_FAILURE = 'ADD_WISHLIST_FAILURE';
export const ADD_WISHLIST_CLEAR = 'ADD_WISHLIST_CLEAR';

export const FETCH_WISHLIST_REQUEST = 'FETCH_WISHLIST_REQUEST';
export const FETCH_WISHLIST_SUCCESS = 'FETCH_WISHLIST_SUCCESS';
export const FETCH_WISHLIST_FAILURE = 'FETCH_WISHLIST_FAILURE';

export const REMOVE_WISHLIST_REQUEST = 'REMOVE_WISHLIST_REQUEST';
export const REMOVE_WISHLIST_SUCCESS = 'REMOVE_WISHLIST_SUCCESS';
export const REMOVE_WISHLIST_FAILURE = 'REMOVE_WISHLIST_FAILURE';
export const REMOVE_WISHLIST_CLEAR = 'REMOVE_WISHLIST_CLEAR';
